version: "3"
services:

  mfpad:
    image: mio101/php_node_scripts
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
      MEMC_HOST: memcached
      MEMC_PORT: 11211
    depends_on:
      - memcached
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  memcached:
    image: memcached:1.5.8
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "11211:11211"
