version: "3"
services:

  mfpad:
    build: ./mfpad/
    ports:
      - "80:80"
    # volumes:
    #   - ./mfpad/html:/var/www/html
    # environment:
    #   MEMC_HOST: memcached
    #   MEMC_PORT: 11211
    depends_on:
      - memcached
    network_mode: "host"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  memcached:
    image: memcached:1.5.8-alpine
    ports:
      - "11211:11211"
